- standarized whosson init script.
Changed files:
    whoson.init -> 1.2

diff --git a/whoson.init b/whoson.init
--- a/whoson.init
+++ b/whoson.init
@@ -5,30 +5,38 @@
 # chkconfig:	345 40 65
 # description:	whosond - implementation of WHOSON protocol
 #
+# processname:	whosond
+# config:	/etc/whoson.conf
 
-# Source function library.
+# Source function library
 . /etc/rc.d/init.d/functions
 
-# Get config.
+# Get network config
 . /etc/sysconfig/network
 
-# Check that networking is up.
-if [ "${NETWORKING}" == "no" ]
-then
-	exit 0
-fi
+# Get service config
+[ -f /etc/sysconfig/whoson ] && . /etc/sysconfig/whoson
 
-[ -f %{_sbindir}/whosond ] || exit 0
+# Check that networking is up.
+if [ "${NETWORKING}" = "no" ]; then
+	echo "WARNING: Networking is down. Whoson service can't be runed."
+	exit 1
+fi
 
 # See how we were called.
 case "$1" in
   start)
-	show "Starting whosond: "
-	daemon whosond
+	# Check if the service is already running?
+	if [ ! -f /var/lock/subsys/whoson ]; then
+		show "Starting whosond"
+		daemon whosond
+	else
+		echo "whosond already is running"
+	fi
 	touch /var/lock/subsys/whosond
 	;;
   stop)
-	show "Stopping whosond services: "
+	show "Stopping whosond services"
 	killproc whosond
 	rm -f /var/lock/subsys/whosond
 	;;
